<?php

namespace Sinmar\ApartmentBundle\Entity;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name)
    {
        $sql = "SELECT n FROM SinmarApartmentBundle:Apartment n WHERE n.name LIKE '%" . $name ."%' ";

        $query = $this->getEntityManager()->createQuery($sql);

        $results = $query->getResult();

        return $results;
    }

}